name: Daily Version Checker

# Run the workflow every day at midnight (UTC)
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script
      - name: Run Version Checker Script
        run: python check_version.py